export const BALL_ANSWERS = [
  'Yes. The way forward is open.',
  'Yes—act before doubt takes over.',
  'Yes. Conditions are in your favor.',
  'Proceed. This is a real opportunity.',
  'Yes, but keep the commitment small.',
  'Yes. The important pieces are aligned.',
  'Yes. What you are asking for is within reach.',
  'Trust your first yes.',
  'Unclear. More information is coming.',
  'Unclear. Take one honest action, then ask again.',
  'Not yet. Wait for the missing fact.',
  'The outcome is still taking shape.',
  'Wait. Today is not the day to decide.',
  'Wait for a second clear sign.',
  'Ask a simpler, more direct question.',
  'Uncertain. Look at the situation from another angle.',
  'No. The closed path may be protecting you.',
  'No. Do not force this opening.',
  'No. The answer is moving away from you.',
  'Not in the form you currently imagine.',
  'Let this go before it consumes more of your attention.',
  'No. The likely cost is greater than the benefit.',
  'No. The useful moment has passed.',
  'Choose another direction.',
];

const fortuneOpenings = [
  'A conversation you have been avoiding',
  'A small change in your routine',
  'An offer that arrives unexpectedly',
  'A detail you nearly missed',
  'A boundary stated clearly',
  'A task finished in private',
  'A familiar person returning',
  'A decision made without an audience',
  'A question you ask directly',
  'A plan you simplify',
  'An apology given freely',
  'A quiet hour alone',
];

const fortuneClosings = [
  'will make the next step easier to see.',
  'will matter more than it first appears.',
  'will change what you are ready to choose.',
  'will bring a hidden concern into the open.',
  'will save more time than waiting for certainty.',
  'will show you which part of the plan is real.',
  'will return energy you have been wasting.',
  'will clarify who is willing to meet you halfway.',
  'will ask for a response sooner than expected.',
  'will confirm what you already know.',
  'will create room for a better option.',
  'will feel small at first and important later.',
];

export const FORTUNES = fortuneOpenings.flatMap((opening) =>
  fortuneClosings.map((closing) => `${opening} ${closing}`),
);

export const FORTUNE_PROMPTS = [
  'What answer are you waiting for even though you already know enough?',
  'Which invitation needs a clear yes or no?',
  'Who could help if you asked directly?',
  'What small fact changes your understanding of the situation?',
  'Where would a quiet act of courage help most?',
  'What ending are you ready to acknowledge?',
  'What can you complete today?',
  'What familiar approach no longer works?',
  'Whose approval are you still waiting for?',
  'Which boundary would give you energy back?',
  'What message are you ready to answer honestly?',
  'What private habit is beginning to change your life?',
];
